version: '3'
services:
  substrate:
    build: blockchain
    container_name: substrate
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
      - "5000:5000"
      - "6000:6000"
  test:
    build: test
    container_name: test
    tty: true
    stdin_open: true
    env_file:
      - ./env/integration.env
    volumes:
      - ./test:/app
      - /app/node_modules
      - /app/build
      - /app/src/zksync/node_modules
      - /app/src/zksync/build
      - /app/src/zksync/sdk/zksync.js/node_modules
      - /app/src/zksync/sdk/zksync.js/build
      - /app/src/zksync/infrastructure/zk/node_modules
      - /app/src/zksync/infrastructure/zk/build
      - /app/src/zksync/contracts/build
  setup:
    build:
      context: test
      dockerfile: DockerSetup
    container_name: setup
    tty: true
    stdin_open: true
    env_file:
      - ./env/integration.env
    volumes:
      - ./test:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - substrate
  operator:
    image: zksync/server
    container_name: operator
    tty: true
    stdin_open: true
    env_file:
      - ./env/common.env
    volumes:
      - ./test/build:/contracts/build
    ports:
      - "3000:3000"
      - "3031:3031"
      - "3030:3030"
      - "8088:8088"
  prover:
    image: zksync/prover
    container_name: prover
    tty: true
    stdin_open: true
    env_file:
      - ./env/common.env
  postgres:
    build: ./test/src/zksync/core/lib/storage/migrations
    container_name: postgres
    tty: true
    stdin_open: true
    ports:
      - "5432:5432"
  ticker:
    image: "matterlabs/dev-ticker:latest"
    container_name: ticker
    ports:
      - "9876:9876"
